version: "3.9"
services:
  embodiedai:
    build:
      context: ./backend
      dockerfile: Dockerfile
    image: embodiedai-mvp:latest
    container_name: embodiedai-mvp
    environment:
      - RMW_IMPLEMENTATION=rmw_cyclonedds_cpp
    volumes:
      - ./backend:/app
    network_mode: bridge
    ports:
      - "8080:8080"   # MCP HTTP
      - "9876:9876"   # Rerun Web Viewer
    restart: unless-stopped

